###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: device-api
  name: device-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: device-api
  template:
    metadata:
      labels:
        cluster: management
        component: device-api
    spec:
      volumes:
      - name: authx-config
        configMap:
          name: device-api-authx-config
      containers:
      - name: device-api
        image: nalejregistry.azurecr.io/nalej/device-api:__NPH_VERSION
        env:
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: authx-secret
              key: secret
        volumeMounts:
        - name: authx-config
          mountPath: "/nalej/config"
          readOnly: true
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--deviceManagerAddress=device-manager.nalej:6010"
        - "--authxAddress=authx.nalej:8810"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
