kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    cluster: management
    component: device-api
  name: device-api-authx-config
  namespace: __NPH_NAMESPACE
data:
  # Primitives: ORG, APPS, RESOURCES, PROFILE
  authx-config.json: |
    {"allows_all":false,
     "permissions": {
       "/device_api.Applications/RetrieveTargetApplications":{"must":["DEVICE"]},
       "/device_api.Applications/RetrieveEndpoints":{"must":["DEVICE"]},
       "/device_api.Device/RetrieveDeviceLabels":{"must":["DEVICE"]}
     }
    }
