###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: device-api
  name: device-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: device-api
  template:
    metadata:
      labels:
        cluster: management
        component: device-api
    spec:
      containers:
        - name: device-api
          image: __NPH_REGISTRY_NAMESPACE/device-api:__NPH_VERSION
          imagePullPolicy: Always
          args:
            - "run"
            - "--deviceManagerAddress=device-manager.__NPH_NAMESPACE:6010"
            - "--authxAddress=authx.__NPH_NAMESPACE:8810"
            - "--authHeader=authorization"
            - "--authConfigPath=/nalej/config/authx-config.json"
            - "--applicationsManagerAddress=application-manager.__NPH_NAMESPACE:8910"
            - "--threshold=100"
          securityContext:
            runAsUser: 2000
          volumeMounts:
            - name: authx-config
              mountPath: "/nalej/config"
              readOnly: true
      volumes:
        - name: authx-config
          configMap:
            name: device-api-authx-config
