###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: device-api
  name: device-api
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: device-api
  template:
    metadata:
      labels:
        cluster: management
        component: device-api
    spec:
      containers:
      - name: device-api
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/device-api:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--deviceManagerAddress=device-manager.__NPH_NAMESPACE:6010"
        - "--authHeader=authorization"
        - "--authSecret=$(AUTH_SECRET)"
        - "--authConfigPath=/nalej/config/authx-config.json"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
