parameters:
  namespace: "nalej"

jobs:
  - job: DeployComponent

    pool:
      vmImage: "Ubuntu-16.04"

    variables:
      - group: docker-registries
      - name: componentList
        value: "device-api"

    steps:
      - task: DownloadSecureFile@1
        inputs:
          secureFile: ci_kubeconfig.yaml
        displayName: "Get K8S configuration file"

      - script: |
          mkdir -p dist/yaml/{appcluster,mngtcluster}
          for component in $(componentList); do
            if [ -d components/$component/appcluster ]; then
              mkdir -p dist/yaml/appcluster
              cp components/$component/appcluster/*.yaml dist/yaml/appcluster/.
            fi
            if [ -d components/$component/mngtcluster ]; then
              mkdir -p dist/yaml/mngtcluster
              cp components/$component/mngtcluster/*.yaml dist/yaml/mngtcluster/.
            fi
          done
        displayName: "Prepare YAML file workspace"

      - script: |
          version=$(cat ../../../.version)
          if [ "$(ls -A)" ]; then
            for file in *.yaml
            do
                sed -i -e "s/__NPH_VERSION/$version/g" $file
                sed -i -e "s/__NPH_NAMESPACE/$NAMESPACE/g" $file
                sed -i -e "s/__NPH_REGISTRY_NAMESPACE/nalej/g" $file
                sed -i -e "s/__NPH_REGISTRY/$(stagingDockerRegistry)/g" $file
            done
          fi
        env:
          NAMESPACE: ${{ parameters.namespace }}
        workingDirectory: dist/yaml/mngtcluster
        displayName: "Render Management platform YAML files"
      
      - script: |
          version=$(cat ../../../.version)
          if [ "$(ls -A)" ]; then
            for file in *.yaml
            do
                sed -i -e "s/__NPH_VERSION/$version/g" $file
                sed -i -e "s/__NPH_NAMESPACE/$NAMESPACE/g" $file
                sed -i -e "s/__NPH_REGISTRY_NAMESPACE/nalej/g" $file
                sed -i -e "s/__NPH_REGISTRY/$(stagingDockerRegistry)/g" $file
            done
          fi
        env:
          NAMESPACE: ${{ parameters.namespace }}
        workingDirectory: dist/yaml/appcluster
        displayName: "Render Application platform YAML files"

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: k8sYAMLfiles
          targetPath: dist/yaml
        displayName: "Publish K8S YAML files"
