variables:
  - group: docker-registries
  - name: componentList
    value: "device-api"
  - name: namespace
    value: $(Build.SourceVersion)-$(Build.BuildId)
  - name: kubeconfig
    value: $(Agent.TempDirectory)/ci_kubeconfig.yaml

jobs:
- job: DeployComponent
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - template: templates/render_yaml.yaml
    parameters:
      namespace: $(namespace)
      componentList: $(componentList)
      dockerRegistry: $(stagingDockerRegistry)

  - task: DownloadSecureFile@1
    inputs:
      secureFile: ci_kubeconfig.yaml
    displayName: "Get K8S configuration file"
  
  - script: |
      kubectl --kubeconfig $(kubeconfig) create ns $(namespace)
    displayName: Create kubernetes namespace

  - template: templates/k8s_deploy.yaml
    parameters:
      kubeconfig: $(kubeconfig)
      platform: mngtcluster
  
  - template: templates/verify_k8s_deploy.yaml
    parameters:
      kubeconfig: $(kubeconfig)
      namespace: $(namespace)
      resourceKind: deployment
      resourceName: device-api

  - script: |
      kubectl --kubeconfig $(kubeconfig) delete ns $(namespace)
    displayName: Delete kubernetes namespace
