jobs:
- job: RandonNamespaceName
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - checkout: none
  
  - task: PythonScript@0
    inputs:
      scriptSource: inline
      script: |
        import random, string
        x = ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(16))
        with open("randomNamespace", "w") as rfile:
          rfile.write(x)
      workingDirectory: $(system.defaultWorkingDirectory)
    displayName: Generate random namespace name
  
  - script: |
      echo '##vso[task.setvariable variable=randomNamespace;isOutput=true]'$(cat randomNamespace)
    workingDirectory: $(system.defaultWorkingDirectory)
    name: generateRandomName
    displayName: Set random namespace as a variable

- job: CreateK8SNamespace
  dependsOn: RandonNamespaceName
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    randomNamespace: $[ dependencies.RandomNamespaceName.outputs['generateRandomName.randomNamespace'] ]
  
  steps:
    - script: echo $(randomNamespace)

# - template: templates/deploy.yaml
