jobs:
- job: RandonNamespaceName
  
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: |
      randomNamespace=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
      echo "##vso[task.setvariable variable=randomNamespace;isOutput=true]$randomNamespace"
    name: generateRandomName

- job: CreateK8SNamespace
  
  dependsOn: RandonNamespaceName
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    randomNamespace: $[ dependencies.RandomNamespaceName.outputs['generateRandomName.randomNamespace'] ]
  steps:
    - script: echo $(randomNamespace)

# - template: templates/deploy.yaml
