variables:
  namespace: 

jobs:
- job: CreateK8SNamespace
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
    - script: |
        echo $(Build.BuildId)
        echo $(Build.BuildNumber)
        echo $(Build.DefinitionName)
        echo $(Build.DefinitionVersion)
        echo $(Build.SourceVersion)
        echo $(System.DefinitionId)
        

# - template: templates/deploy.yaml
